// Code generated by "deep-copy -type DevicesStatusSpec -o deep_copy.generated.go ."; DO NOT EDIT.

package runtime

// DeepCopy generates a deep copy of DevicesStatusSpec.
func (o DevicesStatusSpec) DeepCopy() DevicesStatusSpec {
	var cp DevicesStatusSpec = o
	return cp
}
