// Code generated by "deep-copy -type ServiceSpec -o deep_copy.generated.go ."; DO NOT EDIT.

package v1alpha1

// DeepCopy generates a deep copy of ServiceSpec.
func (o ServiceSpec) DeepCopy() ServiceSpec {
	var cp ServiceSpec = o
	return cp
}
